# This file was generated by GoReleaser. DO NOT EDIT.
cask "iidp" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "cbf33464ad633c9b3d0e2ee5c5919a311540fd076689396dbebb4de3b57f0ea4"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee15f1088091355729275886c88be0c0eaf62ba2174d0602679afdaa0c457134"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "87dc503b30d1d611f7cf933f5dfb29c3c88ec33360394e75d29af98a52a1b90e"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c6741b5097efa0cd724dcc814894678f18a9638e9cad3efa6d93962f36031f3"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "iidp"
  desc "Command line interface to Itema's Internal Developer Platform"
  homepage "https://github.com/Itema-as/iidp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iidp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iidp"]
    end
  end

  # No zap stanza required
end
