# This file was generated by GoReleaser. DO NOT EDIT.
cask "iidp" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "e9ba2e71a477ef86f28f8d39d9b971b390243d86540ddb0c9a57b60ca4a5c6e0"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f463fe98f41ee35c2bf2a0f2d95a16b0d5b2cd35cd3b24a8c819136bbba0b583"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f00c655a80c5b5730c89197dd282b8a5a27a40022e6883a54ff85f125ca5423a"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c18a1e39dd8bde00901079b73c6f5dba942390f9c12b26247d1306755321acf"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "iidp"
  desc "Command line interface to Itema's Internal Developer Platform"
  homepage "https://github.com/Itema-as/iidp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iidp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iidp"]
    end
  end

  # No zap stanza required
end
