# This file was generated by GoReleaser. DO NOT EDIT.
cask "iidp" do
  version "0.3.4"

  on_macos do
    on_arm do
      sha256 "28453ff6087cafba33efdf2e58138f62bd1d947ad572484f75bec3577bd6f8c0"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc128a8284aa44ab4563a1e7dc87ac60674c2b5ab31efeed1226125b8e06d69c"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f0763ad2b4b494a68c075b1117f7f6446edf4ad169cb4bdcfa3cf0f23305c269"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4bd9f0dea6d53b094f4a49e877115bd830a6b3a7bf760f5d2da076651332ab69"
      url "https://github.com/Itema-as/iidp/releases/download/v#{version}/iidp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "iidp"
  desc "Command line interface to Itema's Internal Developer Platform"
  homepage "https://github.com/Itema-as/iidp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iidp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iidp"]
    end
  end

  # No zap stanza required
end
